export const BASE_URL = process.env.NEXT_PUBLIC_PRODUCTION === "true"
    ? process.env.NEXT_PUBLIC_BASE_URL_PRODUCTION
    : process.env.NEXT_PUBLIC_BASE_URL_LOCAL;

export const BASE_API_URL = `${BASE_URL}/${process.env.NEXT_PUBLIC_API_PREFIX_URL}/`

export const MAX_PROFILE_IMAGE_SIZE = process.env.NEXT_PUBLIC_MAX_PROFILE_IMAGE_SIZE ?? 1048576
export const MAX_PROFILE_IMAGE_HEIGHT = process.env.NEXT_PUBLIC_MAX_PROFILE_IMAGE_HEIGHT ?? 1024
export const MAX_PROFILE_IMAGE_WIDTH = process.env.NEXT_PUBLIC_MAX_PROFILE_IMAGE_WIDTH ?? 1024
